const PRODUCTS=[
{id:'p1',name:'Premium Sound Headphones',category:'Electronics',price:59.99,oldPrice:79.99,rating:4.7,reviews:1200,stock:18,badge:'SALE',emoji:'🎧',image:'ChatGPT Image Aug 22, 2026, 02_23_29 AM.png',description:'Comfortable wireless headphones with clear sound and a modern everyday design.'},
{id:'p2',name:'Fitness Tracker Smart Watch',category:'Electronics',price:89,oldPrice:129,rating:4.7,reviews:980,stock:12,badge:'NEW',emoji:'⌚',image:'ChatGPT Image Aug 22, 2026, 02_21_56 AM.png',description:'A smart everyday watch for fitness tracking, notifications and useful daily features.'},
{id:'p3',name:'Waterproof Travel Backpack',category:'Fashion',price:34.5,oldPrice:49.99,rating:4.6,reviews:640,stock:24,badge:'SALE',emoji:'🎒',image:'ChatGPT Image Aug 22, 2026, 02_25_21 AM.png',description:'A durable travel backpack with practical storage for school, travel and everyday use.'},
{id:'p4',name:'Instant Brew Coffee Machine',category:'Electronics',price:45,oldPrice:55,rating:4.5,reviews:410,stock:8,badge:'SALE',emoji:'☕',image:'ChatGPT Image Aug 22, 2026, 02_27_16 AM.png',description:'Compact coffee machine designed for quick, convenient brewing at home.'},
{id:'p5',name:'Spalding Basketball',category:'Sports',price:56,oldPrice:65,rating:4.6,reviews:520,stock:16,badge:'NEW',emoji:'🏀',image:'basketball.png',description:'All-weather basketball built for practice, games and recreational play.'},
{id:'p6',name:'Nintendo Switch OLED',category:'Electronics',price:300,oldPrice:349,rating:4.8,reviews:2100,stock:6,badge:'SALE',emoji:'🎮',image:'nintendo.png',description:'OLED gaming console with vivid display and flexible handheld or docked play.'},
{id:'p7',name:'Golden Rolex Wrist Watch',category:'Fashion',price:250000,oldPrice:275000,rating:4.9,reviews:74,stock:2,badge:'SALE',emoji:'⌚',image:'rolex.png',description:'Luxury-inspired gold wristwatch presentation piece.'},
{id:'p8',name:"Men's Full Accessory Pack",category:'Fashion',price:54,oldPrice:69,rating:4.4,reviews:350,stock:15,badge:'NEW',emoji:'🧢',image:'men.png',description:'A coordinated accessory set for everyday style.'},
{id:'p9',name:'Gold & Black Basketball Shoes',category:'Fashion',price:54,oldPrice:70,rating:4.6,reviews:720,stock:11,badge:'SALE',emoji:'👟',image:'jordan.png',description:'Sporty basketball shoes with a bold gold and black look.'},
{id:'p10',name:'PlayStation 5',category:'Electronics',price:500,oldPrice:549,rating:4.9,reviews:1800,stock:5,badge:'SALE',emoji:'🎮',image:'ps5.png',description:'Next-generation gaming console for immersive games and entertainment.'},
{id:'p11',name:'High-Speed Work Laptop',category:'Electronics',price:749,oldPrice:799,rating:4.6,reviews:310,stock:9,badge:'NEW',emoji:'💻',image:'ChatGPT Image Aug 22, 2026, 02_28_30 AM.png',description:'A capable laptop for school, work, browsing and everyday productivity.'},
{id:'p12',name:'Classic Cotton T-Shirt',category:'Fashion',price:19.99,oldPrice:25,rating:4.4,reviews:870,stock:30,badge:'NEW',emoji:'👕',image:'ChatGPT Image Aug 22, 2026, 02_30_05 AM.png',description:'A comfortable classic cotton shirt for everyday wear.'},
{id:'p13',name:'Fresh Red Apples (1kg)',category:'Groceries',price:4.5,oldPrice:5.5,rating:4.5,reviews:290,stock:25,badge:'SALE',emoji:'🍎',image:'ChatGPT Image Aug 22, 2026, 02_31_31 AM.png',description:'Fresh red apples suitable for snacks, breakfast and cooking.'},
{id:'p14',name:'Ergonomic Wireless Mouse',category:'Electronics',price:25,oldPrice:32,rating:4.5,reviews:440,stock:19,badge:'NEW',emoji:'🖱️',image:'ChatGPT Image Aug 22, 2026, 02_32_09 AM.png',description:'Comfortable wireless mouse designed for everyday computer use.'},
{id:'p15',name:'Warm Waterproof Jacket',category:'Fashion',price:85,oldPrice:99,rating:4.6,reviews:260,stock:10,badge:'SALE',emoji:'🧥',image:'ChatGPT Image Aug 22, 2026, 02_33_11 AM.png',description:'A practical jacket designed for cool and wet weather.'},
{id:'p16',name:'Noise Canceling Headphones',category:'Electronics',price:129,oldPrice:159,rating:4.7,reviews:1500,stock:7,badge:'SALE',emoji:'🎧',image:'Headphones.png',description:'Immersive headphones with a comfortable fit and noise-reducing design.'},
{id:'p17',name:'6-in-1 Multiport USB-C Adapter',category:'Electronics',price:29,oldPrice:39,rating:4.4,reviews:620,stock:20,badge:'SALE',emoji:'🔌',image:'USB.png',description:'A handy multiport adapter for connecting common devices and accessories.'},
{id:'p18',name:'20,000mAh Fast Charging Power Bank',category:'Electronics',price:35,oldPrice:45,rating:4.5,reviews:760,stock:14,badge:'SALE',emoji:'🔋',image:'Power bank.png',description:'Portable high-capacity power bank for charging compatible devices.'},
{id:'p19',name:'Classic Polarized Sunglasses',category:'Fashion',price:18.5,oldPrice:25,rating:4.3,reviews:510,stock:22,badge:'SALE',emoji:'🕶️',image:'Glass.png',description:'Classic sunglasses with polarized lenses and a simple everyday frame.'},
{id:'p20',name:'Minimalist RFID Leather Wallet',category:'Fashion',price:24,oldPrice:30,rating:4.5,reviews:390,stock:17,badge:'NEW',emoji:'👛',image:'Wallet.png',description:'Slim wallet design with practical everyday card and cash storage.'},
{id:'p21',name:'Pasture-Raised Large Eggs (12ct)',category:'Groceries',price:4.25,oldPrice:5.25,rating:4.6,reviews:330,stock:18,badge:'SALE',emoji:'🥚',image:'EGG.png',description:'A convenient 12-count pack of large eggs.'},
{id:'p22',name:'Fresh Whole Milk (1 Gallon)',category:'Groceries',price:3.89,oldPrice:4.49,rating:4.5,reviews:280,stock:13,badge:'SALE',emoji:'🥛',image:'Milk.png',description:'Fresh whole milk for breakfast, drinks and cooking.'},
{id:'p23',name:'RGB Mechanical Keyboard',category:'Electronics',price:65,oldPrice:79,rating:4.7,reviews:930,stock:9,badge:'NEW',emoji:'⌨️',image:'Keyboard.png',description:'Mechanical keyboard with RGB lighting for gaming and productivity.'},
{id:'p24',name:'Casual Minimalist Sneakers',category:'Fashion',price:65,oldPrice:79,rating:4.5,reviews:440,stock:12,badge:'NEW',emoji:'👟',image:'Shoe (1).png',description:'Simple everyday sneakers designed for casual outfits.'},
{id:'p25',name:'Slim Fit Stretch Denim Jeans',category:'Fashion',price:49.99,oldPrice:59.99,rating:4.4,reviews:610,stock:20,badge:'SALE',emoji:'👖',image:'Jean.png',description:'Stretch denim jeans with a classic slim fit.'},
{id:'p26',name:'Organic Bananas (Bunch)',category:'Groceries',price:2.99,oldPrice:3.49,rating:4.6,reviews:480,stock:21,badge:'SALE',emoji:'🍌',image:'Banana.png',description:'Fresh bananas sold as a convenient bunch.'},
{id:'p27',name:'Organic Whole Wheat Bread',category:'Groceries',price:3.1,oldPrice:3.8,rating:4.5,reviews:210,stock:16,badge:'NEW',emoji:'🍞',image:'Bread.jpg',description:'Whole wheat bread for breakfast, sandwiches and snacks.'}
];
const CART_KEY='sarugan_quickcart_cart',WISH_KEY='sarugan_quickcart_wishlist';
const money=n=>'$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCartCount()}function getWish(){try{return JSON.parse(localStorage.getItem(WISH_KEY)||'[]')}catch{return[]}}function saveWish(w){localStorage.setItem(WISH_KEY,JSON.stringify(w))}function cartCount(){return getCart().reduce((s,i)=>s+i.qty,0)}function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cartCount())}
function toast(msg){let t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),1800)}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;let c=getCart(),i=c.find(x=>x.id===id);if(i)i.qty=Math.min(i.qty+qty,p.stock);else c.push({id,qty:Math.min(qty,p.stock)});saveCart(c);toast(p.name+' added to cart')}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}function changeQty(id,d){let c=getCart(),i=c.find(x=>x.id===id),p=PRODUCTS.find(x=>x.id===id);if(!i)return;i.qty=Math.max(1,Math.min(p.stock,i.qty+d));saveCart(c);renderCart()}
function toggleWish(id){let w=getWish();w=w.includes(id)?w.filter(x=>x!==id):[...w,id];saveWish(w);renderProducts();toast(w.includes(id)?'Added to wishlist':'Removed from wishlist')}
function productCard(p){const w=getWish().includes(p.id),disc=Math.round((1-p.price/p.oldPrice)*100);return `<article class="product-card"><div class="product-media"><span class="badge ${p.badge==='NEW'?'new':''}">${p.badge}</span><button class="wish ${w?'on':''}" onclick="toggleWish('${p.id}')">${w?'♥':'♡'}</button><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><div class="fallback-art" style="display:none">${p.emoji}</div></div><div class="product-info"><div class="category">${p.category}</div><a class="product-name" href="product.html?id=${p.id}">${p.name}</a><div class="rating"><span>★★★★★</span> ${p.rating} (${p.reviews.toLocaleString()})</div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span><span class="discount">${disc}% OFF</span></div><div class="stock">● In Stock · ${p.stock} left</div><div class="card-actions"><button class="small-btn quick" onclick="location.href='product.html?id=${p.id}'">Quick View</button><button class="small-btn add" onclick="addToCart('${p.id}')">Add to Cart</button></div></div></article>`}
function renderProducts(list=PRODUCTS){document.querySelectorAll('[data-product-grid]').forEach(g=>g.innerHTML=list.map(productCard).join(''));updateCartCount()}
function param(k){return new URLSearchParams(location.search).get(k)}
function setupHeader(){updateCartCount();const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});const h=document.querySelector('.hamburger'),m=document.querySelector('.mobile-menu');if(h&&m)h.onclick=()=>m.classList.toggle('open')}
function hideLoader(){const l=document.getElementById('loadingScreen');if(!l)return;window.addEventListener('load',()=>setTimeout(()=>l.classList.add('hide'),120))}
function renderCart(){const box=document.getElementById('cartItems'),empty=document.getElementById('cartEmpty'),summary=document.getElementById('summary');if(!box)return;const c=getCart();if(!c.length){box.innerHTML='';empty.style.display='block';summary.style.display='none';updateCartCount();return}empty.style.display='none';summary.style.display='block';box.innerHTML=c.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return `<div class="cart-item"><div class="cart-thumb"><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${p.emoji}</span></div><div><b>${p.name}</b><div class="category">${p.category}</div><div class="stock">● In Stock</div></div><strong>${money(p.price*i.qty)}</strong><div class="qty"><button onclick="changeQty('${p.id}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty('${p.id}',1)">+</button></div><button class="remove" onclick="removeFromCart('${p.id}')">Remove</button></div>`}).join('');let sub=c.reduce((s,i)=>s+PRODUCTS.find(x=>x.id===i.id).price*i.qty,0);document.getElementById('subtotal').textContent=money(sub);document.getElementById('total').textContent=money(sub);updateCartCount()}
function renderDetail(){const root=document.getElementById('detailRoot');if(!root)return;const p=PRODUCTS.find(x=>x.id===param('id'))||PRODUCTS[0];root.innerHTML=`<div class="detail-media"><img src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${p.emoji}</span></div><div><div class="category">${p.category}</div><h1>${p.name}</h1><div class="rating"><span style="color:#f5a623">★★★★★</span> ${p.rating} · ${p.reviews.toLocaleString()} reviews</div><div class="price-row" style="margin-top:15px"><span class="price" style="font-size:28px">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span></div><div class="stock">● In Stock · ${p.stock} available</div><p>${p.description}</p><ul class="detail-list"><li>Quality checked product</li><li>Secure checkout experience</li><li>Easy returns on eligible items</li></ul><div class="qty-lg"><button onclick="detailQty(-1)">−</button><span id="detailQty">1</span><button onclick="detailQty(1)">+</button></div><div class="detail-actions"><button class="btn btn-primary" onclick="addToCart('${p.id}',Number(document.getElementById('detailQty').textContent))">🛒 Add to Cart</button><button class="btn btn-outline" onclick="buyNow('${p.id}')">⚡ Buy Now</button></div></div>`}
function detailQty(d){const e=document.getElementById('detailQty'),p=PRODUCTS.find(x=>x.id===param('id'))||PRODUCTS[0];e.textContent=Math.max(1,Math.min(p.stock,Number(e.textContent)+d))}function buyNow(id){addToCart(id,Number(document.getElementById('detailQty')?.textContent||1));location.href='cart.html'}
function initCatalog(){const grid=document.querySelector('[data-product-grid]');if(!grid||!document.getElementById('catalogSearch'))return;let state={q:param('q')||'',cat:param('cat')||'all',sort:param('sort')||'popular'};const search=document.getElementById('catalogSearch');search.value=state.q;const apply=()=>{let a=PRODUCTS.filter(p=>(state.cat==='all'||p.category.toLowerCase()===state.cat)&&(p.name+' '+p.category).toLowerCase().includes(state.q.toLowerCase()));if(state.sort==='low')a.sort((x,y)=>x.price-y.price);if(state.sort==='high')a.sort((x,y)=>y.price-x.price);if(state.sort==='new')a.sort((x,y)=>Number(y.id.slice(1))-Number(x.id.slice(1)));if(state.sort==='popular')a.sort((x,y)=>y.rating-x.rating);renderProducts(a);document.getElementById('resultCount').textContent=a.length+' products'};search.oninput=e=>{state.q=e.target.value;apply()};document.getElementById('sortSelect').value=state.sort;document.getElementById('sortSelect').onchange=e=>{state.sort=e.target.value;apply()};document.querySelectorAll('[data-filter]').forEach(b=>{if(b.dataset.filter===state.cat)b.classList.add('active');b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.cat=b.dataset.filter;apply()}});apply()}
document.addEventListener('DOMContentLoaded',()=>{setupHeader();hideLoader();renderProducts();renderCart();renderDetail();initCatalog();document.querySelectorAll('[data-search-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();location.href='categories.html?q='+encodeURIComponent(f.querySelector('input').value)});document.getElementById('checkoutBtn')?.addEventListener('click',()=>{if(!getCart().length)return toast('Your cart is empty');toast('Checkout demo ready — connect your payment provider here.')});document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();document.getElementById('contactSuccess').style.display='block';e.target.reset()})});
